// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Announcement struct {
	ID               uuid.UUID `json:"id"`
	Description      string    `json:"description"`
	AnnouncementDate time.Time `json:"announcement_date"`
	CreatedBy        uuid.UUID `json:"created_by"`
	CreatedAt        time.Time `json:"created_at"`
}

type Contract struct {
	ID           uuid.UUID `json:"id"`
	EmployeeID   uuid.UUID `json:"employee_id"`
	ContractType string    `json:"contract_type"`
	Period       int32     `json:"period"`
	StartDate    time.Time `json:"start_date"`
	EndDate      time.Time `json:"end_date"`
	Attachment   string    `json:"attachment"`
	CreatedAt    time.Time `json:"created_at"`
}

type Employee struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Name        string    `json:"name"`
	Dob         time.Time `json:"dob"`
	Avatar      string    `json:"avatar"`
	Phone       string    `json:"phone"`
	Gender      string    `json:"gender"`
	JobTitle    string    `json:"job_title"`
	Department  string    `json:"department"`
	Address     string    `json:"address"`
	IsPresent   bool      `json:"is_present"`
	JoiningDate time.Time `json:"joining_date"`
	CreatedAt   time.Time `json:"created_at"`
}

type Leave struct {
	ID           uuid.UUID `json:"id"`
	EmployeeID   uuid.UUID `json:"employee_id"`
	ApprovedByID uuid.UUID `json:"approved_by_id"`
	Approved     bool      `json:"approved"`
	LeaveType    string    `json:"leave_type"`
	Description  string    `json:"description"`
	StartDate    time.Time `json:"start_date"`
	EndDate      time.Time `json:"end_date"`
	LeaveCount   int16     `json:"leave_count"`
	CreatedAt    time.Time `json:"created_at"`
	Seen         bool      `json:"seen"`
}

type Payroll struct {
	ID          uuid.UUID `json:"id"`
	EmployeeID  uuid.UUID `json:"employee_id"`
	BasicSalary string    `json:"basic_salary"`
	Tin         string    `json:"tin"`
	BankName    string    `json:"bank_name"`
	BankAccount string    `json:"bank_account"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Role struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Token struct {
	Hash   []byte    `json:"hash"`
	UserID uuid.UUID `json:"user_id"`
	Expiry time.Time `json:"expiry"`
	Scope  string    `json:"scope"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	RoleID       uuid.UUID `json:"role_id"`
	Email        string    `json:"email"`
	PasswordHash []byte    `json:"password_hash"`
	IsEnabled    bool      `json:"is_enabled"`
	CreatedAt    time.Time `json:"created_at"`
}
