// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Contract struct {
	ID           uuid.UUID `json:"id"`
	EmployeeID   uuid.UUID `json:"employee_id"`
	ContractType string    `json:"contract_type"`
	Period       int32     `json:"period"`
	StartDate    time.Time `json:"start_date"`
	EndDate      time.Time `json:"end_date"`
	Attachment   string    `json:"attachment"`
}

type Employee struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Dob         time.Time `json:"dob"`
	Avatar      string    `json:"avatar"`
	Phone       string    `json:"phone"`
	Gender      string    `json:"gender"`
	JobTitle    string    `json:"job_title"`
	Department  string    `json:"department"`
	Address     string    `json:"address"`
	JoiningDate time.Time `json:"joining_date"`
}

type Leave struct {
	ID          uuid.UUID `json:"id"`
	EmployeeID  uuid.UUID `json:"employee_id"`
	ApprovedBy  uuid.UUID `json:"approved_by"`
	Approved    bool      `json:"approved"`
	Description string    `json:"description"`
	StartDate   time.Time `json:"start_date"`
	EndDate     time.Time `json:"end_date"`
	LeaveCount  int16     `json:"leave_count"`
	CreatedAt   time.Time `json:"created_at"`
	Seen        bool      `json:"seen"`
}

type Role struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Token struct {
	Hash   []byte    `json:"hash"`
	UserID uuid.UUID `json:"user_id"`
	Expiry time.Time `json:"expiry"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	RoleID       uuid.UUID `json:"role_id"`
	Email        string    `json:"email"`
	PasswordHash []byte    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
