name: Go Test Build and Deploy

on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.0
      
    - name: Test
      run: go test -v ./...
      
    - name: Build
      run: go build -v -o hr ./cmd/api

    - uses: actions/upload-artifact@v4
      with:
          name: hr-artifact
          path: ./hr

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: hr-artifact
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.PORT }}
           source: ./hr
           target: "/home/${{ secrets.USERNAME }}/Documents/hr"

      - name: Start hr Backend service and Reload Nginx
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.PORT }}
           script: |
               cd /home/${{ secrets.USERNAME }}/Documents/hr
               chmod +x hr
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl stop hr.service 
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl start hr.service 
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl reload nginx

 
